# Logistic Regression

In [14]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

In [15]:
# Load train and validation data
X_train = pd.read_csv('../../../data/processed/splits/X_train.csv').drop(columns=['Date'], errors='ignore')
y_train = pd.read_csv('../../../data/processed/splits/y_train_clf.csv')['target_direction']
X_val = pd.read_csv('../../../data/processed/splits/X_val.csv').drop(columns=['Date'], errors='ignore')
y_val = pd.read_csv('../../../data/processed/splits/y_val_clf.csv')['target_direction']

In [16]:
# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

In [17]:
# Train Logistic Regression with cross-validation and regularization
logreg_cv = LogisticRegressionCV(
    Cs=20,
    cv=5,
    penalty='l2',
    solver='lbfgs',
    multi_class='multinomial',
    max_iter=1000,
    scoring='accuracy',
    n_jobs=-1,
    refit=True
)
logreg_cv.fit(X_train_scaled, y_train)

LogisticRegressionCV(Cs=20, cv=5, max_iter=1000, multi_class='multinomial',
                     n_jobs=-1, scoring='accuracy')

In [18]:
# Evaluate on validation set
val_preds = logreg_cv.predict(X_val_scaled)
print('Validation Accuracy:', accuracy_score(y_val, val_preds))
print('Confusion Matrix:\n', confusion_matrix(y_val, val_preds))
print('Classification Report:\n', classification_report(y_val, val_preds))

Validation Accuracy: 0.405189620758483
Confusion Matrix:
 [[  0 143   0]
 [  0 203   0]
 [  0 155   0]]
Classification Report:
               precision    recall  f1-score   support

          -1       0.00      0.00      0.00       143
           0       0.41      1.00      0.58       203
           1       0.00      0.00      0.00       155

    accuracy                           0.41       501
   macro avg       0.14      0.33      0.19       501
weighted avg       0.16      0.41      0.23       501



f:\ANA\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
f:\ANA\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
f:\ANA\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
# Show best regularization strength
print('Best C (Inverse Regularization):', logreg_cv.C_)

Best C (Inverse Regularization): [0.0001 0.0001 0.0001]


In [20]:
# Check validation accuracy for reference
val_preds = logreg_cv.predict(X_val_scaled)
print('Validation Accuracy:', accuracy_score(y_val, val_preds))

Validation Accuracy: 0.405189620758483


In [21]:
# Evaluate on X_test
X_test = pd.read_csv('../../../data/processed/splits/X_test.csv').drop(columns=['Date'], errors='ignore')
y_test = pd.read_csv('../../../data/processed/splits/y_test_clf.csv')['target_direction']
X_test_scaled = scaler.transform(X_test)
test_preds = logreg_cv.predict(X_test_scaled)
print('Test Accuracy:', accuracy_score(y_test, test_preds))
print('Confusion Matrix:\n', confusion_matrix(y_test, test_preds))
print('Classification Report:\n', classification_report(y_test, test_preds))

Test Accuracy: 0.40319715808170514
Confusion Matrix:
 [[  0 120   0]
 [  0 227   0]
 [  0 216   0]]
Classification Report:
               precision    recall  f1-score   support

          -1       0.00      0.00      0.00       120
           0       0.40      1.00      0.57       227
           1       0.00      0.00      0.00       216

    accuracy                           0.40       563
   macro avg       0.13      0.33      0.19       563
weighted avg       0.16      0.40      0.23       563



f:\ANA\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
f:\ANA\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
f:\ANA\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
